### ISSUE TITLE
Move TksAwsSesMessage from `implementation` to `interface`

### ISSUE THREAD

**Issue by edwinyzh** [gmurt/ksAws#1] opened 2020-10-29 13:16 UTC
Sometimes we need to construct a TksAwsSesMessage object, but currently it's not accessible by outside units since it's declared in the `implementation' section.

Would you move it to the `interface` section?

**Edit 1**: BTW, do you access pull requests now?

**Comment by gmurt** [comment] 2020-10-29 13:21
Hi Edwin,

No you don't need to access the class directly. It is exposed via an interface in the ksAwSes unit. 

It is by design that the implementation is not accessible directly. 

Please use IksAwsSesMessage instead.  You can create this using the CreateSesMessage(); function.


e.g. 

var
  AMsg: IksAwsSesMessage;
begin
  AMsg := CreateSesMessage('someone@somewhere.com', 'me@home.com', 'blah', 'hello there!');
end;

**Comment by gmurt** [comment] 2020-10-29 13:22
If you need any extra functionality added to the IksAwsSesMessage interface, let me know ;-)

**Comment by gmurt** [comment] 2020-10-29 13:29
Yes, I'm happy to consider pull requests.  Are they not enabled?  (I'm not a very experienced user of Git)

**Comment by edwinyzh** [comment] 2020-10-29 13:56
> Hi Edwin,
> 
> No you don't need to access the class directly. It is exposed via an interface in the ksAwSes unit.
> 
> It is by design that the implementation is not accessible directly.
> 
> Please use IksAwsSesMessage instead. You can create this using the CreateSesMessage(); function.
> 
> e.g.
> 
> var
> AMsg: IksAwsSesMessage;
> begin
> AMsg := CreateSesMessage('[someone@somewhere.com](mailto:someone@somewhere.com)', '[me@home.com](mailto:me@home.com)', 'blah', 'hello there!');
> end;

Thanks for your reply, @gmurt .

I think there are cases where people need to, for example, add more recipients? Or specify BCC? I think it's not possible now with the currently version. 
**edit 1** so I guess a better option would be to allow operate the `IksAwsSesMessage` interface instead :)

**Comment by edwinyzh** [comment] 2020-10-29 13:57
> Yes, I'm happy to consider pull requests. Are they not enabled? (I'm not a very experienced user of Git)

It's not a technical question, but a policy issue, Just want to make sure you as a person will accept it :)

**Comment by gmurt** [comment] 2020-10-29 15:58
To add more recipients, simply add them via the TStrings propertes in the interface. 

e.g.
```
var
  AMsg: IksAwsSesMessage;
  ASes: IksAwsSES;
begin
  AMsg := CreateSesMessage('someone@somewhere.com', 'me@home.com', 'blah', 'hello there!');
  AMsg.CC.Add('john@smith.com');
  ASes.SendEmail(AMsg);
end;
```

**Comment by gmurt** [comment] 2020-10-29 15:59
I'll close this issue. Any further questions, let me know.

**Closed as completed by gmurt** 2020-10-29 15:59 UTC
